<?xml version="1.0"?>
<package format="2">
  <name>simulation</name>
  <version>1.0.0</version>
  <description>Gazebo simulation configuration</description>
  <maintainer email="napleo@example.com">NAPLEO</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>gazebo_ros</depend>
  <depend>gazebo_ros_pkgs</depend>

  <export></export>
</package>
